rabbitmq:
  image: tutum/rabbitmq
  environment:
    - RABBITMQ_PASS=mypass
  ports:
    - "5672:5672"  # we forward this port because it's useful for debugging
    - "15672:15672"  # here, we can access rabbitmq management plugin

redis:
  image: redis:2.8.19

development:
  build: .
  ports:
    - 8000:8000
  links:
    - db:db
    - rabbitmq:rabbit
    - redis:redis
  command: python manage.py runserver 0.0.0.0:8000

scraper:
  build: scraper/
  volumes:
    - .:/usr/src/app/scraper
  command: tail -f /dev/null
  links:
    - rabbitmq:rabbitmq
    - redis:redis

db:
  image: mysql:5.7.7
  volumes:
    - /home/mysql:/var/lib/mysql
  environment:
    - MYSQL_DATABASE=productnu
    - MYSQL_USER=productnu
    - MYSQL_PASSWORD=superpassword
    - MYSQL_ROOT_PASSWORD=superpassword

worker:
  build: .
  command: ./run_celery.sh
  volumes:
    - .:/app
  links:
    - db:db
    - rabbitmq:rabbit